"""Tuning values shared by the current torso/tree/full-body lab comparisons.

Changing these values affects newly generated solves, not saved viewer results.
Fractions scale residuals; they are not hard limits. Native length bounds are
reported separately so diagnostics and the viewer describe the actual solver.
"""
from skellyforge import _native

SPINE_LENGTH_EQUALITY_SCALE_MM = _native.DEFAULT_LENGTH_EQUALITY_SCALE
SHOULDER_LINKAGE_SCALE_MM = _native.DEFAULT_LINKAGE_SCALE
SHOULDER_LINKAGE_ACCELERATION_SCALE_MM_S2 = _native.DEFAULT_LINKAGE_ACCELERATION_SCALE

POSITION_RESIDUAL_SCALE_MM = 10.
ROOT_ACCELERATION_SCALE_MM_S2 = 3000.
ANGULAR_ACCELERATION_SCALE_RAD_S2 = 20.
REST_POSE_RESIDUAL_SCALE_RAD = 2.
LENGTH_PRIOR_FRACTION = _native.DEFAULT_LENGTH_PRIOR_FRACTION
WIDER_LENGTH_PRIOR_FRACTION = 0.5
SHORTENING_BIASED_COMPRESSION_FRACTION = 0.5
SHORTENING_BIASED_EXTENSION_FRACTION = 0.25
LENGTH_ACCELERATION_SCALE_MM_S2 = _native.DEFAULT_LENGTH_ACCELERATION_SCALE
AXIAL_LENGTH_MINIMUM_FRACTION = _native.AXIAL_LENGTH_MINIMUM_FRACTION
AXIAL_LENGTH_MAXIMUM_FRACTION = _native.AXIAL_LENGTH_MAXIMUM_FRACTION
AXIAL_LENGTH_BOUND_FRACTIONS = (AXIAL_LENGTH_MINIMUM_FRACTION, AXIAL_LENGTH_MAXIMUM_FRACTION)
BOUND_CONTACT_TOLERANCE_MM = 1e-5
DIRECT_MAPPING_TOLERANCE_MM = 1e-8
TARGET_RANK_TOLERANCE_MM = 1e-8
