# Release archives only: no Git checkouts, submodules, or Git mutations.
include(FetchContent)
set(BUILD_TESTING OFF CACHE BOOL "" FORCE)
set(BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(BUILD_BENCHMARKS OFF CACHE BOOL "" FORCE)
set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
set(PROVIDE_UNINSTALL_TARGET OFF CACHE BOOL "" FORCE)
set(MINIGLOG ON CACHE BOOL "" FORCE)
set(GFLAGS OFF CACHE BOOL "" FORCE)
set(SUITESPARSE OFF CACHE BOOL "" FORCE)
set(LAPACK OFF CACHE BOOL "" FORCE)
set(USE_CUDA OFF CACHE BOOL "" FORCE)
set(ACCELERATESPARSE OFF CACHE BOOL "" FORCE)
set(SCHUR_SPECIALIZATIONS OFF CACHE BOOL "" FORCE)
set(EIGEN_BUILD_DOC OFF CACHE BOOL "" FORCE)
FetchContent_Declare(eigen URL https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz
  URL_HASH SHA256=8586084f71f9bde545ee7fa6d00288b264a2b7ac3607b974e54d13e7162c1c72)
FetchContent_MakeAvailable(eigen)
set(Eigen3_DIR "${eigen_BINARY_DIR}" CACHE PATH "" FORCE)
FetchContent_Declare(ceres URL https://github.com/ceres-solver/ceres-solver/archive/refs/tags/2.2.0.tar.gz
  URL_HASH SHA256=12efacfadbfdc1bbfa203c236e96f4d3c210bed96994288b3ff0c8e7c6f350d4)
FetchContent_MakeAvailable(ceres)
install(FILES "${ceres_SOURCE_DIR}/LICENSE" DESTINATION skellyforge/licenses RENAME CERES_LICENSE COMPONENT python)
install(FILES "${eigen_SOURCE_DIR}/COPYING.MPL2" DESTINATION skellyforge/licenses RENAME EIGEN_LICENSE COMPONENT python)
